apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  annotations:
    build.appstudio.openshift.io/pipeline: '{"name":"docker-build","bundle":"latest"}'
    build.appstudio.openshift.io/request: configure-pac-no-mr
  name: kn-ekb-test-committed-offset-116
spec:
  componentName: kn-ekb-test-committed-offset-116
  application: serverless-operator-136 
  source:
    git:
      url: https://github.com/openshift-knative/eventing-kafka-broker.git
      context: 
      dockerfileUrl: openshift/ci-operator/knative-test-images/committed-offset/Dockerfile
      revision: release-v1.16
